### ISSUE TITLE
Refactors

### ISSUE THREAD

**Issue by kelvinst** [Teamweek/holidefs#3]
- [x] Move `on`, `year` and `between` from `Holidefs.Store` to `Holidefs` (#5)
- [x] Rename `Holidefs.Store` to `Holidefs.Definition.Store` (#5)
- [x] Rename `Holidefs.DefinitionRule` to `Holidefs.Definition.Rule` (#5)
- [x] Rename `Holidefs.Event` to `Holidefs.Holiday`(#5)
