### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by kelvinst** [Teamweek/holidefs#4]
Checklist extracted from https://medium.com/shedul-tech-blog/ultimate-guide-to-preparing-and-releasing-elixir-open-source-package-like-a-pro-d64a0f86d012.

The article is quite a good read. ;)

- [x] Improve README.md with Usage (#5)
- [x] Add LICENSE file to MIT license (#5)
- [x] Add CHANGELOG.md (#5)
- [x] Add README and CHANGELOG as doc extras (#5)
- [x] Check generated documentation (#5)
- [x] Configure `readme` as the main doc page (#5)
- [x] Configure CI
- [x] Configure CodeClimate to run `credo`
- [x] Configure the package
- [x] Publish it to hexpm
- [x] Add badges to README
